# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polytrader2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import plotly

#<-----Class used to select screen type(portfolio,stocks, etc.)--->
class MyList(QtWidgets.QListWidget):
    def __init__(self,mainWindow,widgetList):
        QtWidgets.QListWidget.__init__(self)
        self.listParent = QtWidgets.QWidget(mainWindow)
        self.widgetList = widgetList
        self.add_items()
        self.itemClicked.connect(self.item_click)

    def add_items(self):
        count = 0
        iconArray = ["FlaskServer/stock-1.png","FlaskServer/portfolio.png","FlaskServer/trade.png","FlaskServer/research.png","FlaskServer/funds.png"]
        for item_text in self.widgetList:
            item = QtWidgets.QListWidgetItem(item_text)
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(iconArray[count]), QtGui.QIcon.Normal, QtGui.QIcon.On)
            item.setIcon(icon)
            item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsEnabled)
            font = QtGui.QFont()
            font.setUnderline(False)
            font.setKerning(False)
            item.setFont(font)
            self.addItem(item)
            count = count + 1

            
            

    def item_click(self, item):
        print( item, str(item.text()))
        if(str(item.text())=="Portfolio"):
            ui.stackedWidget.setCurrentIndex(0)
        if(str(item.text())=="Stocks"):
            ui.stackedWidget.setCurrentIndex(1)
        if(str(item.text())=="Trade"):
            ui.stackedWidget.setCurrentIndex(4)
        if(str(item.text())=="Research & Ideas"):
            ui.stackedWidget.setCurrentIndex(2)
        if(str(item.text())=="Bank & Financing"):
            ui.stackedWidget.setCurrentIndex(3)

class Ui_MainWindow(object):
    def __init__(self,token,idNumber,tableQuantity=1):
        self.token = token
        self.idNumber = idNumber
        self.tableQuantity = tableQuantity
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1333, 1308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.searchWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchWidget.sizePolicy().hasHeightForWidth())
        self.searchWidget.setSizePolicy(sizePolicy)
        self.searchWidget.setMinimumSize(QtCore.QSize(900, 200))
        self.searchWidget.setMaximumSize(QtCore.QSize(16777215, 202))
        self.searchWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.searchWidget.setStyleSheet("background:white;")
        self.searchWidget.setObjectName("searchWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.searchWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 881, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_9 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.widget_9.setMinimumSize(QtCore.QSize(300, 50))
        self.widget_9.setObjectName("widget_9")
        self.label_13 = QtWidgets.QLabel(self.widget_9)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 91, 16))
        self.label_13.setStyleSheet("font-size:18px;")
        self.label_13.setObjectName("label_13")
        self.textEdit = QtWidgets.QTextEdit(self.widget_9)
        self.textEdit.setGeometry(QtCore.QRect(100, 10, 441, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_13.raise_()
        self.textEdit.raise_()
        self.verticalLayout_2.addWidget(self.widget_9)
        #<=== STOCK TABLE WIDGET =====>
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        rows = self.qtyForRow()
        self.tableWidget.setRowCount(rows)
        
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.stockTableItemLoader()
        self.tableWidget.itemClicked.connect(self.editItem)

        self.verticalLayout_2.addWidget(self.tableWidget, 0, QtCore.Qt.AlignTop)
        self.gridLayout_2.addWidget(self.searchWidget, 0, 1, 1, 1)
        #<--- Use of mylist class ---->
        #self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        
        #<-------- LIST WIDGETS FOR PAGE SELECTOR(Above code replaces this ---- >
        """
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(False)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("FlaskServer/stock-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("FlaskServer/portfolio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("FlaskServer/trade.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("FlaskServer/research.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("FlaskServer/funds.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        """
        
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(256, 500))
        self.widget.setStyleSheet("color:white;\n"
"background:white;\n"
"border:1px solid grey;")
        self.widget.setObjectName("widget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 251, 501))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setStyleSheet("border:none;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.HLine)
        self.stackedWidget.setMidLineWidth(-1)
        self.stackedWidget.setProperty("page", "")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_2 = QtWidgets.QWidget(self.page_2)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 261, 501))
        self.widget_2.setStyleSheet("border:1px solid grey;")
        self.widget_2.setObjectName("widget_2")
        self.verticalFrame = QtWidgets.QFrame(self.widget_2)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 0, 261, 501))
        self.verticalFrame.setMaximumSize(QtCore.QSize(16777207, 16777215))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.verticalFrame)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_3.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_3.setStyleSheet("height:50px; border:none")
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label.setStyleSheet("color:black; font-size:12px;")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_3.setStyleSheet("color:black; font-size:12px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_7 = QtWidgets.QWidget(self.verticalFrame)
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_7.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_7.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_7.setStyleSheet("height:50px; border:none")
        self.widget_7.setObjectName("widget_7")
        self.label_9 = QtWidgets.QLabel(self.widget_7)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_9.setStyleSheet("color:black;font-size:12px;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_10.setStyleSheet("color:black;font-size:12px;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(self.verticalFrame)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_6.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_6.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_6.setStyleSheet("height:50px; border:none")
        self.widget_6.setObjectName("widget_6")
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_7.setStyleSheet("color:black;font-size:12px;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_6)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_8.setStyleSheet("color:black;font-size:12px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_4 = QtWidgets.QWidget(self.verticalFrame)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_4.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_4.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_4.setStyleSheet("height:50px; border:none")
        self.widget_4.setObjectName("widget_4")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_2.setStyleSheet("color:black;font-size:12px;")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_4.setStyleSheet("color:black;font-size:12px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.verticalFrame)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_5.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_5.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_5.setStyleSheet("height:50px; border:none")
        self.widget_5.setObjectName("widget_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_5.setStyleSheet("color:black;font-size:12px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_6.setStyleSheet("color:black;font-size:12px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_8 = QtWidgets.QWidget(self.verticalFrame)
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_8.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_8.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_8.setStyleSheet("height:50px; border:none")
        self.widget_8.setObjectName("widget_8")
        self.label_11 = QtWidgets.QLabel(self.widget_8)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_11.setStyleSheet("color:black;font-size:12px;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_8)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_12.setStyleSheet("color:black;font-size:12px;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.widget_8)
        self.stackedWidget.addWidget(self.page_2)
        #<---begin page3 stock page ---->
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.widget_10 = QtWidgets.QWidget(self.page_3)
        self.widget_10.setGeometry(QtCore.QRect(0, 0, 261, 501))
        self.widget_10.setStyleSheet("border:1px solid grey;")
        self.widget_10.setObjectName("widget_10")
        self.verticalFrame_2 = QtWidgets.QFrame(self.widget_10)
        self.verticalFrame_2.setGeometry(QtCore.QRect(0, 0, 261, 501))
        self.verticalFrame_2.setMaximumSize(QtCore.QSize(16777207, 16777207))
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_11 = QtWidgets.QWidget(self.verticalFrame_2)
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_11.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_11.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_11.setStyleSheet("height:50px; border:none")
        self.widget_11.setObjectName("widget_11")
        self.label_14 = QtWidgets.QLabel(self.widget_11)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_14.setStyleSheet("color:black; font-size:12px;")
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_11)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_15.setStyleSheet("color:black; font-size:12px;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.verticalFrame_2)
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_12.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_12.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_12.setStyleSheet("height:50px; border:none")
        self.widget_12.setObjectName("widget_12")
        self.label_16 = QtWidgets.QLabel(self.widget_12)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_16.setStyleSheet("color:black;font-size:12px;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_12)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_17.setStyleSheet("color:black;font-size:12px;")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.verticalFrame_2)
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_13.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_13.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_13.setStyleSheet("height:50px; border:none")
        self.widget_13.setObjectName("widget_13")
        self.label_18 = QtWidgets.QLabel(self.widget_13)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_18.setStyleSheet("color:black;font-size:12px;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_13)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_19.setStyleSheet("color:black;font-size:12px;")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.verticalFrame_2)
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_14.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_14.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_14.setStyleSheet("height:50px; border:none")
        self.widget_14.setObjectName("widget_14")
        self.label_20 = QtWidgets.QLabel(self.widget_14)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_20.setStyleSheet("color:black;font-size:12px;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_14)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_21.setStyleSheet("color:black;font-size:12px;")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.verticalFrame_2)
        self.widget_15.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_15.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_15.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_15.setStyleSheet("height:50px; border:none")
        self.widget_15.setObjectName("widget_15")
        self.label_22 = QtWidgets.QLabel(self.widget_15)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_22.setStyleSheet("color:black;font-size:12px;")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_15)
        self.label_23.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_23.setStyleSheet("color:black;font-size:12px;")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.verticalFrame_2)
        self.widget_16.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_16.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.widget_16.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.widget_16.setStyleSheet("height:50px; border:none")
        self.widget_16.setObjectName("widget_16")
        self.label_24 = QtWidgets.QLabel(self.widget_16)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_24.setStyleSheet("color:black;font-size:12px;")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.widget_16)
        self.label_25.setGeometry(QtCore.QRect(10, 30, 131, 20))
        self.label_25.setStyleSheet("color:black;font-size:12px;")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.widget_16)
        self.stackedWidget.addWidget(self.page_3)
        #<----Begin page 4 --->
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_26.setStyleSheet("color:black;")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.stackedWidget.addWidget(self.page_4)
        #<----PAGE 5--->
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 261, 451))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_27.setMinimumSize(QtCore.QSize(0, 13))
        self.label_27.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_27.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setStyleSheet("color:black;")
        self.label_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_5.addWidget(self.label_27)
        self.stackedWidget.addWidget(self.page_5)
        #<-----PAGE 6---->
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_6)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 261, 451))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_49 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_49.setMinimumSize(QtCore.QSize(0, 13))
        self.label_49.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_49.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_49.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_49.setStyleSheet("color:black;")
        self.label_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_6.addWidget(self.label_49)
        self.stackedWidget.addWidget(self.page_6)
        
        self.gridLayout_2.addWidget(self.widget, 2, 0, 1, 1)
        self.graphWidget = QtWidgets.QWidget(self.centralwidget)
        self.graphWidget.setMinimumSize(QtCore.QSize(900, 600))
        self.graphWidget.setMaximumSize(QtCore.QSize(900, 700))
        self.graphWidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.graphWidget.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.graphWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.graphWidget.setStyleSheet("background:white")
        self.graphWidget.setObjectName("graphWidget")
        self.graphStack = QtWidgets.QStackedWidget(self.graphWidget)
        self.graphStack.setGeometry(QtCore.QRect(10, 10, 881, 681))
        self.graphStack.setObjectName("graphStack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.graphStack.addWidget(self.page)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.graphStack.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.graphStack.addWidget(self.page_10)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.graphStack.addWidget(self.page_8)
        self.gridLayout_2.addWidget(self.graphWidget, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        #<-------- MENU ITEMS --------->
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1333, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAccount = QtWidgets.QMenu(self.menubar)
        self.menuAccount.setObjectName("menuAccount")
        self.menuStocks = QtWidgets.QMenu(self.menubar)
        self.menuStocks.setObjectName("menuStocks")
        self.menuAnalytics = QtWidgets.QMenu(self.menubar)
        self.menuAnalytics.setObjectName("menuAnalytics")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #<-------- MENU Actions --------->
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave.triggered.connect(self.show_page)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDavid_s_ETrade_Account = QtWidgets.QAction(MainWindow)
        self.actionDavid_s_ETrade_Account.setObjectName("actionDavid_s_ETrade_Account")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionSwitch_Account = QtWidgets.QAction(MainWindow)
        self.actionSwitch_Account.setObjectName("actionSwitch_Account")
        self.actionAdd_Account = QtWidgets.QAction(MainWindow)
        self.actionAdd_Account.setObjectName("actionAdd_Account")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.action.setObjectName("action")
        self.page_7 = QtWidgets.QAction(MainWindow)
        self.page_7.setObjectName("page_7")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuAccount.addAction(self.actionDavid_s_ETrade_Account)
        self.menuAccount.addAction(self.actionLogout)
        self.menuAccount.addAction(self.actionSwitch_Account)
        self.menuAccount.addAction(self.actionAdd_Account)
        self.menuStocks.addAction(self.actionSearch)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAccount.menuAction())
        self.menubar.addAction(self.menuStocks.menuAction())
        self.menubar.addAction(self.menuAnalytics.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.listWidget = MyList(self.centralwidget,['item1', 'item2', 'item3','item4','item5'])
        self.listWidget.setMinimumSize(QtCore.QSize(256, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(256, 199))
        self.listWidget.setSizeIncrement(QtCore.QSize(0, 7))
        self.listWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.actionClose.triggered.connect(self.page_3.show)
        self.listWidget.itemActivated['QListWidgetItem*'].connect(self.verticalFrame.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def qtyForRow(self):
        positions = self.positionRequest()
        count=0
        for x in positions["positions"]:
            count = count + 1
        return count
    def editItem(self,item):
        print(item.row())
        ui.stackedWidget.setCurrentIndex(1)
        

    
    #<========= Creates table item for the stock ======>
    def stockTableItemLoader(self):
        positions = self.positionRequest()
        for x in range(0,len(positions["positions"])):
            print("item loading: " + str(x))
            item = QtWidgets.QTableWidgetItem()
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setVerticalHeaderItem(x, item)
            item = QtWidgets.QTableWidgetItem()
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(x, 0, item)
            item = QtWidgets.QTableWidgetItem()
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(x, 1, item)
            item = QtWidgets.QTableWidgetItem()
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(x, 2, item)
            item = QtWidgets.QTableWidgetItem()
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(x, 3, item)
            item = QtWidgets.QTableWidgetItem()
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(x, 4, item)
            item = QtWidgets.QTableWidgetItem()
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(x, 5, item)
            item = QtWidgets.QTableWidgetItem()
            item.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(x, 6, item)
    
        #<========= Fills data for created table item======>
    def stockTableDataLoader(self,_translate):
        positions = self.positionRequest()
        count = 0
        for pos in positions["positions"]:
            print("position data" + pos["symbol"])
            item = self.tableWidget.verticalHeaderItem(count)
            item.setText(_translate("MainWindow", str(count+1)))
            self.tableWidget.setSortingEnabled(False)
            __sortingEnabled = self.tableWidget.isSortingEnabled()
            
            item = self.tableWidget.item(count, 0)
            item.setText(_translate("MainWindow", pos["symbol"]))
            item = self.tableWidget.item(count, 1)
            lastprice =  str(pos["lastPrice"]) 
            item.setText(_translate("MainWindow",lastprice))
            item = self.tableWidget.item(count, 2)
            todaygainloss =  str(pos["todayGainLossPercentage"]) + "%"
            item.setText(_translate("MainWindow",todaygainloss ))
            item = self.tableWidget.item(count, 3)
            totalgainloss =  str(pos["totalGainLossPercentage"]) + "%"
            item.setText(_translate("MainWindow", totalgainloss))
            item = self.tableWidget.item(count, 4)
            item.setText(_translate("MainWindow", str(pos["quantity"])))
            item = self.tableWidget.item(count, 5)
            item.setText(_translate("MainWindow", pos["holdingType"]))
            item = self.tableWidget.item(count, 6)
            item.setText(_translate("MainWindow", "Buy/Sell"))
            self.tableWidget.setSortingEnabled(__sortingEnabled)
            count = count + 1
    
    def stockDataPanelRefresh(self, _translate, stock=""):
        stockData = self.stockRetrieval(stock)
        self.label_14.setText(_translate("MainWindow", "Stock:"))
        self.label_15.setText(_translate("MainWindow", "APPL"))
        self.label_16.setText(_translate("MainWindow", "Price:"))
        self.label_17.setText(_translate("MainWindow", "$734,567.08"))
        self.label_18.setText(_translate("MainWindow", "EPS:"))
        self.label_19.setText(_translate("MainWindow", "$712,567.78"))
        self.label_20.setText(_translate("MainWindow", "Beta"))
        self.label_21.setText(_translate("MainWindow", ".49"))
        self.label_22.setText(_translate("MainWindow", "Return on the Day"))
        self.label_23.setText(_translate("MainWindow", "-0.74%"))
        self.label_24.setText(_translate("MainWindow", "Return since Inception"))
        self.label_25.setText(_translate("MainWindow", "8.99%"))
    
    
    
    def positionRequest(self):
        
        payload = {
                'token':self.token,
                'accountNumber':self.idNumber
        }
        positions = requests.post('https://ems.qa.tradingticket.com/api/v1/position/getPositions', params=payload)
        thePositions = positions.json()
        return thePositions
            

    def show_page(self):
        print('boiii')

    def retranslateUi(self, MainWindow,dataUpdate=[]):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "Search"))
        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Day Gain/Loss"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total Gain/Loss"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Position"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Action"))
        self.stockTableDataLoader(_translate)
        __sortingEnabled = self.listWidget.isSortingEnabled()

        self.listWidget.setSortingEnabled(False)
        #++++++++++++++++++++
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Portfolio"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Stocks"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Trade"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Research & Ideas"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Bank & Financing"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        portfolioData = self.portfolioPageData()
        self.label.setText(_translate("MainWindow", "Portfolio Account:"))
        self.label_3.setText(_translate("MainWindow", "David\'s E-Trade Account"))
        self.label_9.setText(_translate("MainWindow", "Total Account Value:"))
        self.label_10.setText(_translate("MainWindow", str(portfolioData["totalValue"])))
        self.label_7.setText(_translate("MainWindow", "Stocks:"))
        stockValue = str(float(portfolioData["totalValue"]) - float(portfolioData["buyingPower"]))
        self.label_8.setText(_translate("MainWindow", "$"+stockValue))
        self.label_2.setText(_translate("MainWindow", "Cash:"))
        self.label_4.setText(_translate("MainWindow", "$"+str(portfolioData["availableCash"])))
        self.label_5.setText(_translate("MainWindow", "Return on the Day"))
        dayReturn = str(portfolioData["dayPercentReturn"]) + "%"
        self.label_6.setText(_translate("MainWindow", dayReturn))
        self.label_11.setText(_translate("MainWindow", "Absolute Return"))
        self.label_12.setText(_translate("MainWindow", str(portfolioData["totalAbsoluteReturn"])))
        self.stockDataPanelRefresh(_translate)
        self.label_26.setText(_translate("MainWindow", "Research & Ideas Page"))
        self.label_27.setText(_translate("MainWindow", "Banking and Financing"))
        self.label_49.setText(_translate("MainWindow", "Trading Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAccount.setTitle(_translate("MainWindow", "Account"))
        self.menuStocks.setTitle(_translate("MainWindow", "Stocks"))
        self.menuAnalytics.setTitle(_translate("MainWindow", "Analytics"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionDavid_s_ETrade_Account.setText(_translate("MainWindow", "David\'s ETrade - Account"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionSwitch_Account.setText(_translate("MainWindow", "Switch Account"))
        self.actionAdd_Account.setText(_translate("MainWindow", "Add Account"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.action.setText(_translate("MainWindow", "Portfolio"))
        self.page_7.setText(_translate("MainWindow", "portfolio"))

    def stockRetrieval(self,ticker):
        urlstring= "https://api.iextrading.com/1.0/stock/aapl/chart/1d"
        stockData = requests.get(urlstring)
        print("stock feed data")
        print(stockData.json())
        
        

    def portfolioPageData(self):
        payload3 = {
            'token': self.token,
            'accountNumber':self.idNumber
                    }
        accountOverviewData = requests.post('https://ems.qa.tradingticket.com/api/v1/balance/getAccountOverview', params=payload3)
        accountOverview = accountOverviewData.json()
        print(accountOverview)
        return accountOverview
   
        
def stockTableRefresh():
    ui.setupUi(MainWindow)
            
        
        
if __name__=="__main__":
    import sys
    token = sys.argv[1]
    idNumber = sys.argv[2]
    payload = {
        'apiKey':"d50a18d412684656a7481a43d3f9f43a"
        }
    r = requests.post('https://ems.qa.tradingticket.com/api/v1/preference/getBrokerList', params=payload)
    print("available brokers")
    print(r)
    print(r.json())
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(token,idNumber)
    ui.setupUi(MainWindow)
    MainWindow.show()
    stockTableRefresh()
    sys.exit(app.exec_())


