# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polytrader.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 331, 771))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 200, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 227, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 204, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 91, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 121, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(156, 218, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 227, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 204, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 91, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 121, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(156, 218, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 91, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 227, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(111, 204, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 91, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 121, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 91, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 91, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 18, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 182, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.listWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setAutoFillBackground(True)
        self.listWidget.setStyleSheet("background:#121212")
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(40, 70, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#918c8c")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#918c8c")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(130, 170, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 210, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#918c8c")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(130, 210, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(40, 260, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:#918c8c")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(40, 300, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(40, 340, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:#918c8c")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(40, 380, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:white")
        self.label_10.setObjectName("label_10")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(30, 420, 291, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(70, 440, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:#1db954")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(100, 730, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:#1db954")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(80, 680, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:#1db954")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(90, 630, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:#1db954")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(14, 9, 751, 781))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background:#121212")
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        #----Table 1 widget instance ------
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 540, 721, 201))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.tableWidget.setFont(font)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("color:white;\n"
"background:black;\n"
"foreground:black;\n"
"\n"
"\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(len(positionsArray))
        count1 = 0
        #====== Table 1 vertical headers =======
        for number in positionsArray:
            print("table 1 vert headers: " + str(count1))
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(count1, item)
            count1 = count1 + 1
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 85, 255, 247))
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(9, 9, 9))
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        #=====Table 1 widget create =======
        count2=0
        for i in positionsArray:
            print("table widgets 0-4: " + str(count2))
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(count2, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(count2, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(count2, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(count2, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(count2, 4, item)
            count2 = count2 + 1
        
        
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(720, 510, 55, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(30, 520, 55, 16))
        self.label_17.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(130, 520, 55, 16))
        self.label_18.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(260, 520, 55, 16))
        self.label_19.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(380, 520, 55, 16))
        self.label_20.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(500, 520, 61, 21))
        self.label_21.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_21.setObjectName("label_21")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 719, 500))
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 500))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(190, 180, 371, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:white")
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 75))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit.setGeometry(QtCore.QRect(120, 20, 500, 40))
        self.textEdit.setMaximumSize(QtCore.QSize(500, 40))
        self.textEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit.setObjectName("textEdit")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(30, 30, 61, 16))
        self.label_22.setStyleSheet("color:white;\n"
"font-size:20px;")
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 49, 701, 591))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 650))
        self.tableWidget_2.setStyleSheet("color:white;")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(6)
        #====Table 2 vertical space ======
        verticalspacecount = 0
        for number in positionsArray:
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setVerticalHeaderItem(verticalspacecount, item)
            verticalspacecount = verticalspacecount + 1
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        #------------- pTable widget 2 ------------
        entryCount = 0
        for number in positionsArray:
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(entryCount, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(entryCount, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(entryCount, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(entryCount, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(entryCount, 4, item)
            entryCount = entryCount + 1
            
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label_23.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(390, 20, 55, 16))
        self.label_24.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(130, 20, 55, 16))
        self.label_25.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(260, 20, 55, 16))
        self.label_26.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(510, 20, 55, 16))
        self.label_27.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_27.setObjectName("label_27")
        self.groupBox_4.raise_()
        self.groupBox_4.raise_()
        self.tableWidget_2.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.verticalLayout.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1203, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "Portfolio Value"))
        balance = str(david.getBalance())
        self.label_2.setText(_translate("MainWindow", balance))
        self.label_3.setText(_translate("MainWindow", "Stocks"))
        stocks = str(david.getStocks())
        self.label_4.setText(_translate("MainWindow", stocks))
        self.label_5.setText(_translate("MainWindow", "Cash"))
        cash = str(david.getCash())
        self.label_6.setText(_translate("MainWindow", cash))
        self.label_7.setText(_translate("MainWindow", "Buying Power"))
        buyingpower = str(david.getCash())
        self.label_8.setText(_translate("MainWindow", buyingpower))
        self.label_9.setText(_translate("MainWindow", "Withdrawable Cash"))
        wcash = str(david.getWCash())
        self.label_10.setText(_translate("MainWindow", wcash))
        self.label_11.setText(_translate("MainWindow", "Increase Buying Power"))
        self.label_12.setText(_translate("MainWindow", "Tax Documents"))
        self.label_13.setText(_translate("MainWindow", "Account Statements"))
        self.label_14.setText(_translate("MainWindow", "Day Trade Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.tableWidget.setSortingEnabled(False)
    
        vheaderitems = 0
        
        for i in positionsArray:
            print("table 1 vert headers retranslate: " + str(vheaderitems))
            item = self.tableWidget.verticalHeaderItem(vheaderitems)
            v = str(vheaderitems + 1)
            item.setText(_translate("MainWindow", v))
            vheaderitems = vheaderitems + 1
       
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ticker"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Position"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        row = 0
        #====== file table 1 widgets ==========
        for position in positionsArray:
            print("table 1 widgets 0-4 retranslate: " + str(row))
            item = self.tableWidget.item(row,0)
            symbol = position['symbol']
            item.setText(_translate("MainWindow", symbol ))
            item = self.tableWidget.item(row, 1)
            lastPrice = str(position['lastPrice'])
            item.setText(_translate("MainWindow", lastPrice ))
            item = self.tableWidget.item(row, 2)
            quantity = str(position['quantity'])
            item.setText(_translate("MainWindow", quantity ))
            item = self.tableWidget.item(row, 3)
            holdingType = position['holdingType']
            item.setText(_translate("MainWindow", holdingType))
            item = self.tableWidget.item(row, 4)
            item.setText(_translate("MainWindow", "Buy/Sell"))
            row = row + 1
                
        """
        item.setText(_translate("MainWindow", "Apple"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "APPL"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "173.44"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "170.33"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "174.45"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Microsft"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "MSFT"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "20.22"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "23.34"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "23.33"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "FaceBook"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "FB"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "333.44"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "343.34"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "365.34"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Yahoo"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "YH"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "27.99"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "34.55"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "43.33"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Google"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "GG"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "567.66"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "595.00"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "585.55"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "Berkshire"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "BB"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "20305.22"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "20333.33"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("MainWindow", "20405.59"))
        """
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "Stock"))
        self.label_18.setText(_translate("MainWindow", "Price"))
        self.label_19.setText(_translate("MainWindow", "Quantity"))
        self.label_20.setText(_translate("MainWindow", "Position"))
        self.label_21.setText(_translate("MainWindow", "Action"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_15.setText(_translate("MainWindow", "Stock Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Portfolio"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">   Search</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Stocks"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ticker"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Open"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Close"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "Apple"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "APPL"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "Google"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", "GG"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(1, 4)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "FaceBook"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("MainWindow", "FB"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(2, 4)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "Amazon"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("MainWindow", "AMZ"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("MainWindow", "234.22"))
        item = self.tableWidget_2.item(3, 4)
        item.setText(_translate("MainWindow", "234.22"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_23.setText(_translate("MainWindow", "Stock"))
        self.label_24.setText(_translate("MainWindow", "Open"))
        self.label_25.setText(_translate("MainWindow", "Ticker"))
        self.label_26.setText(_translate("MainWindow", "Price"))
        self.label_27.setText(_translate("MainWindow", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Stocks"))


if __name__=="__main__":
    import sys
    import os
    import webbrowser
    import requests
    from user import userData, Stock, StockData
    token = sys.argv[1]
    idNumber = sys.argv[2]
    print(token)
    print(idNumber)
    print(token + "---" + idNumber)
    payload3 = {
            'token':token,
            'accountNumber':idNumber
                    }
    accountOverviewData = requests.post('https://ems.qa.tradingticket.com/api/v1/balance/getAccountOverview', params=payload3)
    accountOverview = accountOverviewData.json()
    print(accountOverview)
    stocksValue = float(accountOverview['totalValue']) - float(accountOverview['buyingPower'])
    david = userData("David",accountOverview['totalValue'],stocksValue,accountOverview['buyingPower'],accountOverview['availableCash'])
    payload4 = {
        'token':token,
        'accountNumber':idNumber
    }
    positionsData = requests.post('https://ems.qa.tradingticket.com/api/v1/position/getPositions', params=payload4)
    positionsObject = positionsData.json()
    positionsArray = positionsObject['positions']
    print(positionsObject)
    print(positionsArray)
    stockTest = Stock("Apple","APPL",333.33,330.95,334.50)
    stockTest2 = Stock("Facebook","FB",983.33,3990.95,3300.50)
    stockTest3 = Stock("Amazon","AMZ",9933.33,930.95,3004.50)
    stocks = []
    stocks.append(stockTest)
    stocks.append(stockTest2)
    stocks.append(stockTest3)
    data = StockData(stocks)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

